// @flow
export const SET_API_KEY = 'SET_API_KEY'
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const ADD_SEARCH_RESULTS = 'ADD_SEARCH_RESULTS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const RESET = 'RESET'
export const EMPTY_CART = 'EMPTY_CART'
export const SUBMIT_RENTAL = 'SUBMIT_RENTAL'

export const ACTIONS = {
  SET_API_KEY,
  SET_SEARCH_TERM,
  ADD_SEARCH_RESULTS,
  ADD_TO_CART,
  RESET,
  EMPTY_CART,
  SUBMIT_RENTAL
}
